"""
==============================================================================
  Mini-Splunk: CLI Client  —  client.py  (Forwarder & Search Head)
==============================================================================
  NSAPDEV Server Application Project
  Author  : Wendel Walter A. Lander
  Course  : NSAPDEV (Server Application Development)
  Term/AY : 2nd Term AY 2025-2026
==============================================================================

COMMAND REFERENCE
─────────────────
  INGEST <file_path> <IP>:<Port>
      Upload a syslog file to the server for parsing and indexing.

  QUERY <IP>:<Port> SEARCH_DATE "<date_string>"
      Find all entries whose timestamp begins with <date_string>.
      e.g.  QUERY 127.0.0.1:65432 SEARCH_DATE "Feb  7"

  QUERY <IP>:<Port> SEARCH_HOST <hostname>
      Find all entries from a specific machine hostname.

  QUERY <IP>:<Port> SEARCH_DAEMON <daemon_name>
      Find all entries generated by a specific service/daemon.

  QUERY <IP>:<Port> SEARCH_SEVERITY <level>
      Find all entries matching a severity (INFO, WARN, ERROR, CRIT, DEBUG).

  QUERY <IP>:<Port> SEARCH_KEYWORD <keyword>
      Find all entries whose message contains the given keyword.

  QUERY <IP>:<Port> COUNT_KEYWORD <keyword>
      Count how many entries contain the given keyword.

  PURGE <IP>:<Port>
      Erase all indexed log entries from the server.

  STATUS <IP>:<Port>
      Show server statistics (entries in memory, total ingested, etc.)

  DUMP <IP>:<Port>
      Displays the first 5 entries of the raw parsed dictionaries sitting in the server's memory

  HELP
      Display this command reference.

  EXIT / QUIT
      Exit the CLI.
==============================================================================
"""

import socket
import os
import sys
import shlex

# ─────────────────────────────────────────────────────────────────────────────
# TRANSPORT LAYER
# ─────────────────────────────────────────────────────────────────────────────
BUFFER_SIZE = 4096


def _send(sock: socket.socket, message: str):
    """Send a length-prefixed UTF-8 message."""
    encoded = message.encode("utf-8")
    length  = len(encoded).to_bytes(4, "big")
    sock.sendall(length + encoded)


def _recv_all(sock: socket.socket, n: int) -> bytes:
    data = b""
    while len(data) < n:
        chunk = sock.recv(min(BUFFER_SIZE, n - len(data)))
        if not chunk:
            break
        data += chunk
    return data


def _recv_message(sock: socket.socket) -> str:
    raw_len = _recv_all(sock, 4)
    if len(raw_len) < 4:
        return ""
    msg_len = int.from_bytes(raw_len, "big")
    return _recv_all(sock, msg_len).decode("utf-8", errors="replace")


def _connect(host: str, port: int, transfer_timeout: int = None) -> socket.socket | None:
    """Open a TCP connection and return the socket, or None on failure."""
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(10)           # Timeout only for the connection handshake
        sock.connect((host, port))
        sock.settimeout(transfer_timeout)  # None = blocking (no timeout) after connected
        return sock
    except ConnectionRefusedError:
        print(f"  [System Message] ERROR: Connection refused at {host}:{port}. "
              "Is the server running?")
    except socket.timeout:
        print(f"  [System Message] ERROR: Connection timed out to {host}:{port}.")
    except Exception as e:
        print(f"  [System Message] ERROR: {e}")
    return None


def _parse_address(addr_str: str) -> tuple[str, int] | None:
    """Parse 'host:port' into (host, port). Returns None on bad format."""
    try:
        host, port_str = addr_str.rsplit(":", 1)
        return host, int(port_str)
    except Exception:
        print(f"  [System Message] ERROR: Invalid address format '{addr_str}'. "
              "Expected <IP_or_DNS>:<Port>")
        return None


# ─────────────────────────────────────────────────────────────────────────────
# COMMAND HANDLERS
# ─────────────────────────────────────────────────────────────────────────────

def cmd_ingest(args: list[str]):
    """INGEST <file_path> <IP>:<Port>"""
    if len(args) < 2:
        print("  [System Message] Usage: INGEST <file_path> <IP>:<Port>")
        return

    file_path = args[0]
    addr_str  = args[1]

    if not os.path.isfile(file_path):
        print(f"  [System Message] ERROR: File not found: '{file_path}'")
        return

    parsed = _parse_address(addr_str)
    if not parsed:
        return
    host, port = parsed

    print(f"  [System Message] Connecting to {host}:{port}…")
    sock = _connect(host, port, transfer_timeout=600)  # 5 min — enough for large files
    if not sock:
        return

    try:
        with open(file_path, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()

        size = len(content.encode("utf-8"))
        print(f"  [System Message] Uploading '{os.path.basename(file_path)}' "
              f"({size / 1024:.1f} KB, {content.count(chr(10))+1} lines)…")

        _send(sock, f"UPLOAD|{size}|{content}")
        response = _recv_message(sock)
        _print_response(response)

    except Exception as e:
        print(f"  [System Message] ERROR during upload: {e}")
    finally:
        sock.close()


def cmd_query(args: list[str]):
    """QUERY <IP>:<Port> <SUB_CMD> <payload>"""
    if len(args) < 2:
        print("  [System Message] Usage: QUERY <IP>:<Port> <SUB_COMMAND> [payload]")
        return

    addr_str = args[0]
    sub_cmd  = args[1].upper()
    payload  = " ".join(args[2:]) if len(args) > 2 else ""

    parsed = _parse_address(addr_str)
    if not parsed:
        return
    host, port = parsed

    valid_cmds = {
        "SEARCH_DATE", "SEARCH_HOST", "SEARCH_DAEMON",
        "SEARCH_SEVERITY", "SEARCH_KEYWORD", "COUNT_KEYWORD",
    }
    if sub_cmd not in valid_cmds:
        print(f"  [System Message] ERROR: Unknown query sub-command '{sub_cmd}'.")
        print(f"  Valid sub-commands: {', '.join(sorted(valid_cmds))}")
        return

    if not payload and sub_cmd != "COUNT_KEYWORD":
        print(f"  [System Message] ERROR: Missing payload for {sub_cmd}.")
        return

    print(f"  [System Message] Sending query {sub_cmd} → {host}:{port}…")
    sock = _connect(host, port)
    if not sock:
        return

    try:
        _send(sock, f"QUERY|{sub_cmd}|{payload}")
        response = _recv_message(sock)
        _print_query_response(response, sub_cmd, payload)
    except Exception as e:
        print(f"  [System Message] ERROR during query: {e}")
    finally:
        sock.close()


def cmd_purge(args: list[str]):
    """PURGE <IP>:<Port>"""
    if not args:
        print("  [System Message] Usage: PURGE <IP>:<Port>")
        return

    parsed = _parse_address(args[0])
    if not parsed:
        return
    host, port = parsed

    confirm = input(f"  [System Message] WARNING: This will erase ALL indexed logs on "
                    f"{host}:{port}. Type YES to confirm: ").strip()
    if confirm.upper() != "YES":
        print("  [System Message] PURGE cancelled.")
        return

    print(f"  [System Message] Connecting to {host}:{port} to purge records…")
    sock = _connect(host, port)
    if not sock:
        return

    try:
        _send(sock, "ADMIN|PURGE|")
        response = _recv_message(sock)
        _print_response(response)
    except Exception as e:
        print(f"  [System Message] ERROR during purge: {e}")
    finally:
        sock.close()


def cmd_status(args: list[str]):
    """STATUS <IP>:<Port>"""
    if not args:
        print("  [System Message] Usage: STATUS <IP>:<Port>")
        return

    parsed = _parse_address(args[0])
    if not parsed:
        return
    host, port = parsed

    sock = _connect(host, port)
    if not sock:
        return

    try:
        _send(sock, "ADMIN|STATUS|")
        response = _recv_message(sock)
        _print_response(response)
    except Exception as e:
        print(f"  [System Message] ERROR: {e}")
    finally:
        sock.close()

def cmd_dump(args: list[str]):
    """DUMP <IP>:<Port> [limit]"""
    if not args:
        print("  [System Message] Usage: DUMP <IP>:<Port> [number_of_entries]")
        return

    parsed = _parse_address(args[0])
    if not parsed:
        return
    host, port = parsed

    limit = args[1] if len(args) > 1 else "5"

    sock = _connect(host, port)
    if not sock:
        return

    try:
        _send(sock, f"ADMIN|DUMP|{limit}")
        response = _recv_message(sock)
        parts = response.split("|", 1)
        if parts[0] == "DUMP":
            print(f"\n  [Server Response — RAM Snapshot]\n")
            print(parts[1] if len(parts) > 1 else "(empty)")
        else:
            _print_response(response)
    except Exception as e:
        print(f"  [System Message] ERROR: {e}")
    finally:
        sock.close()


# ─────────────────────────────────────────────────────────────────────────────
# RESPONSE RENDERERS
# ─────────────────────────────────────────────────────────────────────────────

def _print_response(raw: str):
    if not raw:
        print("  [Server Response] (no response received)")
        return

    parts  = raw.split("|", 2)
    status = parts[0].upper() if parts else ""

    if status == "SUCCESS":
        msg = parts[1] if len(parts) > 1 else ""
        print(f"\n  [Server Response] SUCCESS: {msg}")

    elif status == "STATUS":
        msg = "|".join(parts[1:]) if len(parts) > 1 else ""
        print(f"\n  [Server Response] {msg}")

    elif status == "ERROR":
        msg = parts[1] if len(parts) > 1 else raw
        print(f"\n  [Server Response] ERROR: {msg}")

    else:
        print(f"\n  [Server Response] {raw}")


def _print_query_response(raw: str, sub_cmd: str, payload: str):
    if not raw:
        print("  [Server Response] (no response received)")
        return

    parts  = raw.split("|", 2)
    status = parts[0].upper() if parts else ""

    if status == "RESULTS":
        n    = parts[1] if len(parts) > 1 else "?"
        body = parts[2] if len(parts) > 2 else ""

        label_map = {
            "SEARCH_DATE":     f"date '{payload}'",
            "SEARCH_HOST":     f"host '{payload}'",
            "SEARCH_DAEMON":   f"daemon '{payload}'",
            "SEARCH_SEVERITY": f"severity '{payload}'",
            "SEARCH_KEYWORD":  f"keyword '{payload}'",
        }
        label = label_map.get(sub_cmd, payload)

        print(f"\n  [Server Response] Found {n} matching entries for {label}:")
        if body.strip():
            for line in body.strip().splitlines():
                print(f"    {line}")
        else:
            print("    (no matching entries)")

    elif status == "COUNT":
        count = parts[1] if len(parts) > 1 else "?"
        print(f"\n  [Server Response] The keyword '{payload}' appears "
              f"in {count} indexed log entry/entries.")

    elif status == "ERROR":
        msg = parts[1] if len(parts) > 1 else raw
        print(f"\n  [Server Response] ERROR: {msg}")

    else:
        print(f"\n  [Server Response] {raw}")


# ─────────────────────────────────────────────────────────────────────────────
# HELP TEXT
# ─────────────────────────────────────────────────────────────────────────────

_HELP = """
┌──────────────────────────────────────────────────────────────┐
│         Mini-Splunk  —  CLI Client Command Reference         │
└──────────────────────────────────────────────────────────────┘

  INGEST <file_path> <IP>:<Port>
      Upload a syslog file to the server for parsing and indexing.

  QUERY <IP>:<Port> SEARCH_DATE "<date>"
      Return all log entries matching a date prefix (e.g. "Feb  7").

  QUERY <IP>:<Port> SEARCH_HOST <hostname>
      Return all entries from a specific machine (e.g. SYSSVR1).

  QUERY <IP>:<Port> SEARCH_DAEMON <daemon>
      Return all entries from a specific service (e.g. sshd).

  QUERY <IP>:<Port> SEARCH_SEVERITY <level>
      Filter by severity: INFO | WARN | ERROR | CRIT | DEBUG

  QUERY <IP>:<Port> SEARCH_KEYWORD <word>
      Return entries whose message body contains <word>.

  QUERY <IP>:<Port> COUNT_KEYWORD <word>
      Count entries whose message body contains <word>.

  PURGE <IP>:<Port>
      Erase ALL indexed log entries from server memory.

  STATUS <IP>:<Port>
      Display server statistics (entries in memory, total ingested, etc.)

  DUMP <IP>:<Port>
      Displays the first 5 entries of the raw parsed dictionaries sitting in the server's memory
      
  HELP        Show this help text.
  EXIT/QUIT   Exit the client.
"""


# ─────────────────────────────────────────────────────────────────────────────
# MAIN REPL LOOP
# ─────────────────────────────────────────────────────────────────────────────

def main():
    print("=" * 62)
    print("  Mini-Splunk Syslog Analytics  —  CLI Client")
    print("=" * 62)
    print("  Type HELP for a command reference, EXIT to quit.")
    print("-" * 62)

    while True:
        try:
            raw_input = input("\nclient> ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\n  [System Message] Exiting client. Goodbye.")
            sys.exit(0)

        if not raw_input:
            continue

        try:
            tokens = shlex.split(raw_input)
        except ValueError as e:
            print(f"  [System Message] Parse error: {e}")
            continue

        cmd  = tokens[0].upper()
        args = tokens[1:]

        if cmd in ("EXIT", "QUIT"):
            print("  [System Message] Exiting client. Goodbye.")
            sys.exit(0)

        elif cmd == "HELP":
            print(_HELP)

        elif cmd == "INGEST":
            cmd_ingest(args)

        elif cmd == "QUERY":
            cmd_query(args)

        elif cmd == "PURGE":
            cmd_purge(args)

        elif cmd == "STATUS":
            cmd_status(args)

        elif cmd == "DUMP":
            cmd_dump(args)

        else:
            print(f"  [System Message] Unknown command '{cmd}'. "
                  "Type HELP for a list of available commands.")


if __name__ == "__main__":
    main()
